import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
//👇 Import our second font
import localFont from "next/font/local";

//👇 Configure our local font object
const publicSans = localFont({ src: "./PublicSans-VariableFont_wght.ttf" });

export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        <header className="h-project-header bg-grey-900 w-full flex justify-center items-center xl:hidden">
          <Image
            src="/assets/images/logo-large.svg"
            alt="Finance"
            width={0}
            height={0}
            className="w-auto he-auto"
          />
        </header>
        {children}
      </body>
    </html>
  );
}
