import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-project-header bg-grey-900 w-full flex justify-center items-center absolute">
          <Image
            src="/assets/images/logo-large.svg"
            alt="Finance"
            width={0}
            height={0}
            className="w-auto he-auto"
          />
        </header>
        {children}
      </body>
    </html>
  );
}
